version: '3'
services:
  vue:
    build:
      context: ./docker/vue
    container_name: myapp-vue
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    command: sh -c "cd assets && yarn install && yarn serve"

  go:
    build:
      context: ./docker/go
    container_name: myapp-go
    ports:
      - 8082:8082
    volumes:
      - .:/go/src
    working_dir: /go/src/app
    tty: true
    command: fresh

  db:
    image: mysql:5.7
    container_name: go_db
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./sqls/init:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306 # change default port number
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: docker_db
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: docker_user_pwd

  nginx:
    image: nginx
    depends_on:
      - go
    container_name: myapp-nginx
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  mysql_data:
